"""Curated plant-care lookup (v1.40.12).

A small vision/text LLM (e.g. qwen2.5vl:7b) reliably fails to DIFFERENTIATE
water-use: it returns "moderate / full_sun" for essentially every species. But
water-use (WUCOLS) is exactly what drives the irrigation math, so a wrong value
mis-waters the yard. This table is the deterministic fix: for common Southwest /
low-desert landscape species we ship curated, accurate care so identification only
needs to get the NAME right. The species-ID rail consults this FIRST and only
falls back to the model for species we don't cover.

Pure data + a tolerant matcher (HA-free). WUCOLS categories are the low-desert
(Region 3, "arid/desert") values. Cadences are Arizona-friendly starting points
the user can edit. Every value is bounded again by species_id.validate_suggestion
before it reaches a plant record, so a typo here can't poison the store.
"""

from __future__ import annotations

from typing import Any

# scientific-name key (lowercased) -> care record. `common` is a friendly name;
# `sun`/`wucols`/`preset` use the same enums species_id.validate_suggestion accepts.
# fields: (common, wucols, sun, temp_low_f, temp_high_f, preset, water_days, fert_days, note)
_C = (
    (
        "nerium oleander",
        "Oleander",
        "low",
        "full_sun",
        15,
        115,
        "shrub",
        10,
        0,
        "Very drought-tolerant flowering shrub (all parts toxic).",
    ),
    (
        "carissa macrocarpa",
        "Natal Plum",
        "low",
        "full_sun",
        25,
        110,
        "shrub",
        10,
        60,
        "Dense glossy evergreen shrub with fragrant white flowers.",
    ),
    (
        "lantana camara",
        "Lantana",
        "low",
        "full_sun",
        25,
        115,
        "flower",
        7,
        30,
        "Heat- and drought-tolerant flowering groundcover/shrub.",
    ),
    (
        "leucophyllum frutescens",
        "Texas Ranger",
        "low",
        "full_sun",
        10,
        115,
        "shrub",
        14,
        0,
        "Desert 'Texas sage'; very low water once established.",
    ),
    (
        "dalbergia sissoo",
        "Sissoo",
        "moderate",
        "full_sun",
        20,
        115,
        "tree",
        10,
        60,
        "Fast-growing Sissoo shade tree; deep, infrequent water.",
    ),
    (
        "murraya paniculata",
        "Orange Jasmine",
        "moderate",
        "full_sun",
        30,
        110,
        "shrub",
        7,
        45,
        "Glossy hedge shrub with fragrant white flowers.",
    ),
    (
        "tecoma stans",
        "Yellow Bells",
        "low",
        "full_sun",
        20,
        115,
        "shrub",
        10,
        45,
        "Heat-loving flowering shrub (Esperanza).",
    ),
    (
        "ficus microcarpa",
        "Indian Laurel Fig",
        "moderate",
        "full_sun",
        30,
        115,
        "tree",
        7,
        60,
        "Dense evergreen shade tree; aggressive roots.",
    ),
    (
        "citrus limon",
        "Lemon",
        "moderate",
        "full_sun",
        28,
        110,
        "tree",
        7,
        45,
        "Lemon; deep water + citrus fertilizer 3x/year.",
    ),
    (
        "citrus aurantium",
        "Bitter Orange",
        "moderate",
        "full_sun",
        28,
        110,
        "tree",
        7,
        45,
        "Sour/bitter orange; deep water + citrus feed.",
    ),
    (
        "citrus aurantiifolia",
        "Key Lime",
        "moderate",
        "full_sun",
        30,
        108,
        "tree",
        7,
        45,
        "Key lime; frost-sensitive; deep water + citrus feed.",
    ),
    (
        "citrus",
        "Citrus",
        "moderate",
        "full_sun",
        30,
        110,
        "tree",
        7,
        45,
        "Citrus; deep water + citrus fertilizer.",
    ),
    (
        "rosa",
        "Rose",
        "moderate",
        "full_sun",
        10,
        100,
        "shrub",
        4,
        30,
        "Rose; regular water + feeding through the growing season.",
    ),
    (
        "salvia rosmarinus",
        "Rosemary",
        "low",
        "full_sun",
        15,
        110,
        "shrub",
        10,
        60,
        "Rosemary; drought-tolerant woody herb.",
    ),
    (
        "rosmarinus officinalis",
        "Rosemary",
        "low",
        "full_sun",
        15,
        110,
        "shrub",
        10,
        60,
        "Rosemary; drought-tolerant woody herb.",
    ),
    (
        "zinnia elegans",
        "Zinnia",
        "moderate",
        "full_sun",
        40,
        110,
        "flower",
        4,
        21,
        "Warm-season annual flower; regular water.",
    ),
    (
        "pittosporum tobira",
        "Mock Orange",
        "moderate",
        "full_sun",
        20,
        110,
        "shrub",
        7,
        45,
        "Tough evergreen hedge shrub.",
    ),
    (
        "ilex crenata",
        "Japanese Holly",
        "moderate",
        "partial_sun",
        5,
        100,
        "shrub",
        7,
        45,
        "Small-leaved evergreen shrub; afternoon shade in the desert.",
    ),
    (
        "euonymus japonicus",
        "Japanese Euonymus",
        "moderate",
        "full_sun",
        5,
        105,
        "shrub",
        7,
        45,
        "Glossy evergreen hedge shrub.",
    ),
    (
        "trachelospermum asiaticum",
        "Asiatic Jasmine",
        "moderate",
        "partial_sun",
        20,
        105,
        "flower",
        7,
        30,
        "Evergreen groundcover vine; light shade in the low desert.",
    ),
    (
        "hibiscus rosa-sinensis",
        "Chinese Hibiscus",
        "moderate",
        "full_sun",
        32,
        105,
        "shrub",
        4,
        21,
        "Tropical flowering shrub; frost-sensitive.",
    ),
    (
        "pentas lanceolata",
        "Egyptian Starcluster",
        "moderate",
        "full_sun",
        40,
        105,
        "flower",
        4,
        21,
        "Warm-season flowering annual/perennial; pollinator magnet.",
    ),
    (
        "catharanthus roseus",
        "Annual Vinca",
        "low",
        "full_sun",
        45,
        110,
        "flower",
        5,
        30,
        "Heat-loving flowering annual (Madagascar periwinkle).",
    ),
    (
        "salvia greggii",
        "Autumn Sage",
        "low",
        "full_sun",
        15,
        112,
        "shrub",
        10,
        30,
        "Low-water desert-adapted flowering sage.",
    ),
    (
        "fraxinus velutina",
        "Velvet Ash",
        "moderate",
        "full_sun",
        5,
        115,
        "tree",
        10,
        60,
        "Arizona native shade tree; deep, infrequent water.",
    ),
    (
        "fraxinus uhdei",
        "Tropical Ash",
        "moderate",
        "full_sun",
        20,
        115,
        "tree",
        10,
        60,
        "Fast evergreen shade tree; deep water.",
    ),
    (
        "pyrus calleryana",
        "Bradford Pear",
        "moderate",
        "full_sun",
        0,
        105,
        "tree",
        10,
        45,
        "Ornamental flowering pear tree.",
    ),
    (
        "persea americana",
        "Avocado",
        "high",
        "full_sun",
        30,
        105,
        "tree",
        5,
        45,
        "Avocado; high water, frost-sensitive, wind-protected.",
    ),
    (
        "malus",
        "Apple",
        "moderate",
        "full_sun",
        0,
        100,
        "tree",
        7,
        45,
        "Apple; low-chill varieties for the desert; deep water.",
    ),
    (
        "coreopsis lanceolata",
        "Lance-leaved Coreopsis",
        "low",
        "full_sun",
        10,
        105,
        "flower",
        7,
        21,
        "Drought-tolerant perennial wildflower.",
    ),
    (
        "kalanchoe blossfeldiana",
        "Florist Kalanchoe",
        "low",
        "partial_sun",
        40,
        100,
        "cactus_succulent",
        12,
        60,
        "Succulent; infrequent water, protect from hard frost.",
    ),
    (
        "dianthus barbatus",
        "Sweet William",
        "moderate",
        "full_sun",
        20,
        95,
        "flower",
        5,
        30,
        "Cool-season biennial flower.",
    ),
    (
        "antirrhinum majus",
        "Snapdragon",
        "moderate",
        "full_sun",
        20,
        95,
        "flower",
        4,
        21,
        "Cool-season annual flower.",
    ),
    (
        "salvia farinacea",
        "Mealy Cup Sage",
        "low",
        "full_sun",
        10,
        112,
        "flower",
        10,
        30,
        "Heat-tolerant blue-flowered sage.",
    ),
    (
        "ocimum basilicum",
        "Basil",
        "moderate",
        "full_sun",
        45,
        100,
        "flower",
        3,
        21,
        "Warm-season culinary herb; consistent moisture.",
    ),
    (
        "origanum vulgare",
        "Oregano",
        "low",
        "full_sun",
        20,
        105,
        "shrub",
        10,
        45,
        "Drought-tolerant culinary herb.",
    ),
    (
        "dracaena",
        "Dracaena",
        "moderate",
        "bright_shade",
        45,
        95,
        "shrub",
        10,
        60,
        "Tender foliage plant; bright shade, protect from frost.",
    ),
    # ── v1.45 expansion — common Southwest / low-desert landscape species.
    # Our own compilation (water-use categories are facts; not the WUCOLS
    # dataset, which is UC-copyrighted). Values are hot-arid starting points.
    (
        "ficus carica",
        "Fig",
        "moderate",
        "full_sun",
        10,
        115,
        "tree",
        10,
        45,
        "Edible fig; deep infrequent water, very heat-tolerant, deciduous.",
    ),
    (
        "salvia splendens",
        "Scarlet Sage",
        "moderate",
        "full_sun",
        40,
        105,
        "flower",
        4,
        21,
        "Warm-season flowering annual sage.",
    ),
    (
        "cuphea hyssopifolia",
        "Mexican Heather",
        "low",
        "full_sun",
        25,
        110,
        "flower",
        7,
        30,
        "Heat-tolerant flowering groundcover shrublet.",
    ),
    (
        "parkinsonia",
        "Palo Verde",
        "low",
        "full_sun",
        15,
        118,
        "tree",
        21,
        0,
        "Desert tree; very low water once established, green bark.",
    ),
    (
        "prosopis",
        "Mesquite",
        "low",
        "full_sun",
        0,
        118,
        "tree",
        21,
        0,
        "Desert legume tree; deep, infrequent water.",
    ),
    (
        "chilopsis linearis",
        "Desert Willow",
        "low",
        "full_sun",
        10,
        115,
        "tree",
        14,
        0,
        "Desert tree; low water, summer flowers.",
    ),
    (
        "caesalpinia pulcherrima",
        "Red Bird of Paradise",
        "low",
        "full_sun",
        20,
        118,
        "shrub",
        14,
        30,
        "Heat-loving desert shrub; low water, dies back in frost.",
    ),
    (
        "larrea tridentata",
        "Creosote Bush",
        "very_low",
        "full_sun",
        0,
        120,
        "shrub",
        30,
        0,
        "Sonoran native; extremely drought-tolerant.",
    ),
    (
        "encelia farinosa",
        "Brittlebush",
        "very_low",
        "full_sun",
        15,
        118,
        "shrub",
        21,
        0,
        "Desert native; yellow spring flowers, very low water.",
    ),
    (
        "fouquieria splendens",
        "Ocotillo",
        "very_low",
        "full_sun",
        10,
        120,
        "shrub",
        30,
        0,
        "Desert native; drought-deciduous, minimal water.",
    ),
    (
        "carnegiea gigantea",
        "Saguaro",
        "very_low",
        "full_sun",
        20,
        120,
        "cactus_succulent",
        30,
        0,
        "Iconic Sonoran cactus; rare deep water only.",
    ),
    (
        "opuntia",
        "Prickly Pear",
        "very_low",
        "full_sun",
        0,
        120,
        "cactus_succulent",
        30,
        0,
        "Desert cactus; minimal water.",
    ),
    (
        "agave",
        "Agave",
        "very_low",
        "full_sun",
        15,
        120,
        "cactus_succulent",
        21,
        0,
        "Succulent accent; very low water, sharp spines.",
    ),
    (
        "aloe",
        "Aloe",
        "low",
        "full_sun",
        30,
        115,
        "cactus_succulent",
        14,
        0,
        "Succulent; low water, frost-tender.",
    ),
    (
        "hesperaloe parviflora",
        "Red Yucca",
        "low",
        "full_sun",
        0,
        118,
        "cactus_succulent",
        21,
        0,
        "Desert accent; long red flower spikes, low water.",
    ),
    (
        "dasylirion wheeleri",
        "Desert Spoon",
        "very_low",
        "full_sun",
        5,
        118,
        "cactus_succulent",
        30,
        0,
        "Desert accent; very low water.",
    ),
    (
        "baileya multiradiata",
        "Desert Marigold",
        "very_low",
        "full_sun",
        15,
        115,
        "flower",
        14,
        0,
        "Desert wildflower; very low water.",
    ),
    (
        "ruellia",
        "Ruellia",
        "low",
        "full_sun",
        20,
        118,
        "shrub",
        10,
        30,
        "Heat-loving; purple flowers, low-moderate water.",
    ),
    (
        "calliandra",
        "Fairy Duster",
        "low",
        "full_sun",
        15,
        118,
        "shrub",
        14,
        0,
        "Desert shrub; low water, powderpuff flowers.",
    ),
    (
        "penstemon",
        "Penstemon",
        "low",
        "full_sun",
        0,
        110,
        "flower",
        10,
        0,
        "Desert wildflower; low water, spring bloom.",
    ),
    (
        "bougainvillea",
        "Bougainvillea",
        "low",
        "full_sun",
        30,
        118,
        "shrub",
        10,
        30,
        "Heat-loving vine/shrub; low water once established, frost-tender.",
    ),
    (
        "lantana montevidensis",
        "Trailing Lantana",
        "low",
        "full_sun",
        25,
        115,
        "flower",
        7,
        30,
        "Trailing purple lantana; heat- and drought-tolerant.",
    ),
    (
        "lavandula",
        "Lavender",
        "low",
        "full_sun",
        10,
        105,
        "shrub",
        10,
        30,
        "Mediterranean herb; low water, needs sharp drainage.",
    ),
    (
        "olea europaea",
        "Olive",
        "low",
        "full_sun",
        15,
        115,
        "tree",
        14,
        45,
        "Mediterranean tree; low water; choose fruitless for cleanliness.",
    ),
    (
        "punica granatum",
        "Pomegranate",
        "low",
        "full_sun",
        10,
        115,
        "tree",
        10,
        45,
        "Fruiting tree/shrub; heat-tolerant, low-moderate water.",
    ),
    (
        "vitis vinifera",
        "Grape",
        "moderate",
        "full_sun",
        0,
        115,
        "flower",
        7,
        45,
        "Deciduous fruiting vine; moderate water in season.",
    ),
    (
        "lagerstroemia",
        "Crepe Myrtle",
        "moderate",
        "full_sun",
        0,
        110,
        "tree",
        10,
        45,
        "Summer-flowering deciduous tree; moderate water.",
    ),
    (
        "nandina domestica",
        "Heavenly Bamboo",
        "moderate",
        "partial_sun",
        5,
        110,
        "shrub",
        10,
        45,
        "Evergreen shrub; moderate water, afternoon shade in the desert.",
    ),
    (
        "photinia",
        "Photinia",
        "moderate",
        "full_sun",
        5,
        110,
        "shrub",
        7,
        45,
        "Red-tip hedge shrub; moderate water.",
    ),
    (
        "juniperus",
        "Juniper",
        "low",
        "full_sun",
        0,
        115,
        "shrub",
        14,
        30,
        "Evergreen conifer shrub/tree; low water.",
    ),
    (
        "buxus",
        "Boxwood",
        "moderate",
        "partial_sun",
        0,
        105,
        "shrub",
        7,
        45,
        "Evergreen hedge; moderate water, afternoon shade in the desert.",
    ),
    (
        "gardenia",
        "Gardenia",
        "high",
        "partial_sun",
        30,
        100,
        "shrub",
        4,
        30,
        "Fragrant evergreen; high water, acid soil, shade in the desert.",
    ),
    (
        "hydrangea",
        "Hydrangea",
        "high",
        "bright_shade",
        20,
        95,
        "shrub",
        3,
        30,
        "Shade shrub; high water, struggles in low-desert heat.",
    ),
    (
        "tagetes",
        "Marigold",
        "moderate",
        "full_sun",
        40,
        105,
        "flower",
        4,
        21,
        "Warm-season annual; regular water.",
    ),
    (
        "petunia",
        "Petunia",
        "moderate",
        "full_sun",
        35,
        100,
        "flower",
        3,
        14,
        "Cool-season annual flower; regular water.",
    ),
    (
        "pelargonium",
        "Geranium",
        "moderate",
        "full_sun",
        30,
        100,
        "flower",
        5,
        21,
        "Common bedding geranium; moderate water.",
    ),
    (
        "impatiens",
        "Impatiens",
        "high",
        "bright_shade",
        40,
        95,
        "flower",
        3,
        21,
        "Shade annual; high water, heat-sensitive.",
    ),
    (
        "begonia",
        "Begonia",
        "moderate",
        "bright_shade",
        45,
        95,
        "flower",
        4,
        21,
        "Shade annual/perennial; moderate water.",
    ),
    (
        "helianthus annuus",
        "Sunflower",
        "moderate",
        "full_sun",
        40,
        110,
        "flower",
        5,
        30,
        "Warm-season annual; moderate water.",
    ),
    (
        "plumbago",
        "Plumbago",
        "low",
        "full_sun",
        25,
        115,
        "shrub",
        10,
        30,
        "Blue-flowered heat-lover; low-moderate water.",
    ),
    (
        "dodonaea viscosa",
        "Hopseed Bush",
        "low",
        "full_sun",
        15,
        115,
        "shrub",
        14,
        0,
        "Fast desert-adapted hedge; low water.",
    ),
    (
        "simmondsia chinensis",
        "Jojoba",
        "very_low",
        "full_sun",
        15,
        118,
        "shrub",
        21,
        0,
        "Sonoran native shrub; very low water.",
    ),
    (
        "vauquelinia californica",
        "Arizona Rosewood",
        "low",
        "full_sun",
        5,
        115,
        "shrub",
        14,
        0,
        "Desert native evergreen; low water.",
    ),
    (
        "washingtonia",
        "Fan Palm",
        "low",
        "full_sun",
        15,
        120,
        "tree",
        14,
        30,
        "Desert palm; low water once established.",
    ),
    (
        "phoenix dactylifera",
        "Date Palm",
        "low",
        "full_sun",
        15,
        120,
        "tree",
        14,
        45,
        "Date palm; low-moderate water, extremely heat-tolerant.",
    ),
)

CURATED_CARE: dict[str, dict[str, Any]] = {
    key: {
        "common": common,
        "wucols": wucols,
        "sun": sun,
        "temp_low": tlo,
        "temp_high": thi,
        "preset": preset,
        "water_days": water,
        "fert_days": fert,
        "note": note,
    }
    for (key, common, wucols, sun, tlo, thi, preset, water, fert, note) in _C
}

# keys longest-first so "citrus limon" wins over the generic "citrus" fallback.
_KEYS_BY_LEN = sorted(CURATED_CARE, key=len, reverse=True)


def lookup_care(name: str | None) -> dict[str, Any] | None:
    """Return curated care for a species NAME (matches the scientific name found
    anywhere in the string, e.g. 'Lemon (Citrus limon)'), or None if uncovered.
    Longest key wins, so a specific species beats a genus fallback."""
    if not name or not isinstance(name, str):
        return None
    n = name.lower()
    for key in _KEYS_BY_LEN:
        if key in n:
            return dict(CURATED_CARE[key])
    return None
