"""Schedule data model + in-memory store (pure logic, no HA).

A Schedule is a user-defined recurring rule: run this zone at this
time, for this many minutes, on these weekdays.

The HA-coupled layer (coordinator + storage helper) wraps a
ScheduleStore instance and persists it to HA's storage on every change.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from datetime import date, time
from typing import Any

_VALID_WEEKDAYS = frozenset(range(7))  # 0=Mon .. 6=Sun (ISO)

MODE_WEEKDAYS = "weekdays"
MODE_INTERVAL = "interval"
MODE_INTERVAL_HOURS = "interval_hours"
_VALID_MODES = (MODE_WEEKDAYS, MODE_INTERVAL, MODE_INTERVAL_HOURS)

# Default gap (seconds) between back-to-back zones in a multi-zone schedule.
# Lets the valve close fully before the next opens.
DEFAULT_ZONE_BUFFER_SECONDS = 30


def _parse_hhmm(s: str) -> time:
    """Parse 'HH:MM' into a `time`. Mirrors the inline parse used for
    start_time so interval_end_time uses the same format."""
    hh, mm = s.split(":")
    return time(int(hh), int(mm))


@dataclass(frozen=True)
class ZoneStep:
    """One zone in a multi-zone schedule: which zone, how long.

    Multi-zone schedules carry an ordered tuple of these. The schedule's
    zone_entity_id + duration_minutes mirror the first step for
    backward compat with single-zone consumers.
    """

    zone_entity_id: str
    duration_minutes: int

    def __post_init__(self) -> None:
        if not self.zone_entity_id:
            raise ValueError("ZoneStep.zone_entity_id must be set")
        if self.duration_minutes <= 0:
            raise ValueError(
                f"ZoneStep.duration_minutes must be positive, got {self.duration_minutes}"
            )

    def to_dict(self) -> dict[str, Any]:
        return {
            "zone_entity_id": self.zone_entity_id,
            "duration_minutes": int(self.duration_minutes),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ZoneStep:
        return cls(
            zone_entity_id=data["zone_entity_id"],
            duration_minutes=int(data["duration_minutes"]),
        )


@dataclass(frozen=True)
class Schedule:
    """A single user-defined irrigation rule.

    Frozen — to "edit" a schedule, build a new one with the same id
    and pass it to ScheduleStore.upsert().

    Two recurrence modes:
      • weekdays — fires on the listed days of week, every week
      • interval — fires every interval_days days starting interval_anchor
    """

    id: str
    name: str
    zone_entity_id: str
    start_time: time
    duration_minutes: int
    # weekdays mode: which days of the week (0=Mon..6=Sun, ISO)
    weekdays: tuple[int, ...] = field(default_factory=tuple)
    enabled: bool = True
    # Active period bounds (v1.12). Together with end_date these form an
    # "active window" the schedule lives inside; outside the window it's
    # quiet but not deleted. `start_date` is the first date firings are
    # allowed (None = no lower bound, fires immediately). `end_date` is
    # the last allowed date (None = never end). `repeat_annually` makes
    # the window's month/day repeat each calendar year (seasonal mode);
    # when on, both dates are required and their month/day pair defines
    # the yearly window (year value is ignored on those fields).
    start_date: date | None = None
    repeat_annually: bool = False
    # Optional end_date — if set, schedule stops firing after this date.
    end_date: date | None = None
    # Recurrence mode: "weekdays" (default, current behavior) or "interval"
    mode: str = MODE_WEEKDAYS
    # interval mode: fire every N days starting interval_anchor
    interval_days: int | None = None
    interval_anchor: date | None = None
    # interval_hours mode: fire every N hours from interval_anchor +
    # start_time, continuing across day boundaries.
    interval_hours: int | None = None
    # Optional daily-window cap for interval_hours mode. When set:
    #   • the schedule fires every N hours from `start_time` ON EACH DAY
    #     (re-anchored daily, not continuous across midnight)
    #   • the last firing of a day is the latest one whose start ≤
    #     interval_end_time (inclusive)
    # When None, the legacy continuous-from-anchor behavior is preserved.
    interval_end_time: time | None = None
    # Multi-zone: ordered tuple of ZoneStep. When non-empty the schedule
    # fires zones back-to-back at run time (each waits for the previous to
    # finish, plus DEFAULT_ZONE_BUFFER_SECONDS). The first step mirrors
    # zone_entity_id + duration_minutes so single-zone consumers still work.
    zone_steps: tuple[ZoneStep, ...] = field(default_factory=tuple)
    # Provenance marker (PRD #60). Values: "panel" (created via UI),
    # "calendar" (created via HA calendar create_event), "service"
    # (created via add_schedule service call), or "establishment"
    # (auto-generated by start_establishment). Defaults to "panel" for
    # back-compat with schedules created before v1.10.
    created_via: str = "panel"

    def __post_init__(self) -> None:
        if not self.name or not self.name.strip():
            raise ValueError("name must be non-empty")
        if not self.zone_entity_id:
            raise ValueError("zone_entity_id must be set")
        if self.duration_minutes <= 0:
            raise ValueError(f"duration_minutes must be positive, got {self.duration_minutes}")
        if self.mode not in _VALID_MODES:
            raise ValueError(f"mode must be one of {_VALID_MODES}, got {self.mode!r}")
        if self.mode == MODE_WEEKDAYS:
            if not self.weekdays:
                raise ValueError("weekdays mode requires non-empty weekdays")
            if not set(self.weekdays).issubset(_VALID_WEEKDAYS):
                raise ValueError(f"weekdays must be in 0..6, got {sorted(self.weekdays)}")
        elif self.mode == MODE_INTERVAL:
            if self.interval_days is None or self.interval_days < 1:
                raise ValueError(
                    f"interval mode requires interval_days >= 1, got {self.interval_days}"
                )
            if self.interval_anchor is None:
                raise ValueError("interval mode requires interval_anchor (start date)")
        elif self.mode == MODE_INTERVAL_HOURS:
            if self.interval_hours is None or self.interval_hours < 1:
                raise ValueError(
                    f"interval_hours mode requires interval_hours >= 1, got {self.interval_hours}"
                )
            if self.interval_anchor is None:
                raise ValueError("interval_hours mode requires interval_anchor (start date)")
            # Daily-window cap (optional). When provided, must be strictly
            # after start_time so at least one firing fits in the window.
            if self.interval_end_time is not None and self.interval_end_time <= self.start_time:
                raise ValueError(
                    "interval_end_time must be after start_time "
                    f"(got {self.start_time} → {self.interval_end_time})"
                )
        # interval_end_time is only meaningful for interval_hours mode.
        # Catch misuse in any other mode regardless of the per-mode block above.
        if self.mode != MODE_INTERVAL_HOURS and self.interval_end_time is not None:
            raise ValueError("interval_end_time is only valid in interval_hours mode")
        # Active period (v1.12): when repeat_annually is on, BOTH dates
        # are required and start.month-day must come before end.month-day
        # (we don't support windows that wrap across the year boundary in
        # this release — keeps the per-year membership check unambiguous).
        if self.repeat_annually:
            if self.start_date is None or self.end_date is None:
                raise ValueError("repeat_annually requires both start_date and end_date")
            start_md = (self.start_date.month, self.start_date.day)
            end_md = (self.end_date.month, self.end_date.day)
            if start_md > end_md:
                raise ValueError(
                    "annually-repeating window must not wrap across year-end "
                    "(start month-day must be on/before end month-day)"
                )
        # Multi-zone: first step must agree with the top-level zone/duration
        # (the top-level fields stay authoritative for legacy single-zone
        # consumers; the steps tuple is an extension).
        if self.zone_steps:
            first = self.zone_steps[0]
            if first.zone_entity_id != self.zone_entity_id:
                raise ValueError("zone_steps[0].zone_entity_id must match top-level zone_entity_id")
            if first.duration_minutes != self.duration_minutes:
                raise ValueError(
                    "zone_steps[0].duration_minutes must match top-level duration_minutes"
                )

    def with_changes(self, **overrides: Any) -> Schedule:
        """Return a new Schedule with the given field overrides.

        v1.15 — services.py previously rebuilt Schedule field-by-field
        whenever a single property changed (set_schedule_enabled,
        update_schedule), which silently dropped any field added to the
        dataclass after the handler was written. dataclasses.replace
        keeps the full field set in sync automatically and re-runs
        __post_init__ validation."""
        return replace(self, **overrides)

    def all_steps(self) -> tuple[ZoneStep, ...]:
        """Return the zone sequence. Falls back to a single ZoneStep
        built from the top-level fields when zone_steps is empty (legacy
        single-zone schedule)."""
        if self.zone_steps:
            return self.zone_steps
        return (
            ZoneStep(
                zone_entity_id=self.zone_entity_id,
                duration_minutes=self.duration_minutes,
            ),
        )

    def to_dict(self) -> dict[str, Any]:
        """Serializable form (lists + strings; HA storage stores JSON)."""
        return {
            "id": self.id,
            "name": self.name,
            "zone_entity_id": self.zone_entity_id,
            "start_time": self.start_time.strftime("%H:%M"),
            "duration_minutes": self.duration_minutes,
            "weekdays": list(self.weekdays),
            "enabled": self.enabled,
            "end_date": self.end_date.isoformat() if self.end_date else None,
            "mode": self.mode,
            "interval_days": self.interval_days,
            "interval_anchor": (self.interval_anchor.isoformat() if self.interval_anchor else None),
            "interval_hours": self.interval_hours,
            "interval_end_time": (
                self.interval_end_time.strftime("%H:%M") if self.interval_end_time else None
            ),
            "start_date": self.start_date.isoformat() if self.start_date else None,
            "repeat_annually": self.repeat_annually,
            "zone_steps": [s.to_dict() for s in self.zone_steps],
            "created_via": self.created_via,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Schedule:
        """Parse from the serializable form. Backward compatible with
        pre-v1.4 schedules that have no `mode` field — they're treated
        as weekdays-mode. Pre-v1.8 schedules have no zone_steps."""
        hour_str, minute_str = data["start_time"].split(":")
        end_date_str = data.get("end_date")
        end_date_val = date.fromisoformat(end_date_str) if end_date_str else None
        anchor_str = data.get("interval_anchor")
        anchor_val = date.fromisoformat(anchor_str) if anchor_str else None
        mode = data.get("mode") or MODE_WEEKDAYS
        steps_raw = data.get("zone_steps") or []
        zone_steps = tuple(ZoneStep.from_dict(s) for s in steps_raw)

        return cls(
            id=data["id"],
            name=data["name"],
            zone_entity_id=data["zone_entity_id"],
            start_time=time(int(hour_str), int(minute_str)),
            duration_minutes=int(data["duration_minutes"]),
            weekdays=tuple(data.get("weekdays", ())),
            enabled=bool(data.get("enabled", True)),
            end_date=end_date_val,
            mode=mode,
            interval_days=data.get("interval_days"),
            interval_anchor=anchor_val,
            interval_hours=data.get("interval_hours"),
            interval_end_time=(
                _parse_hhmm(data["interval_end_time"]) if data.get("interval_end_time") else None
            ),
            start_date=(date.fromisoformat(data["start_date"]) if data.get("start_date") else None),
            repeat_annually=bool(data.get("repeat_annually", False)),
            zone_steps=zone_steps,
            created_via=data.get("created_via", "panel"),
        )


class ScheduleStore:
    """In-memory dict of Schedule by id, with serialization helpers.

    Insertion order is preserved (Python dict guarantee since 3.7).
    """

    def __init__(self) -> None:
        self._items: dict[str, Schedule] = {}

    # ── CRUD ────────────────────────────────────────────────────────
    def add(self, schedule: Schedule) -> None:
        """Insert a new schedule. Raises KeyError if id exists — use
        upsert() if you want overwrite semantics."""
        if schedule.id in self._items:
            raise KeyError(f"schedule with id {schedule.id!r} already exists")
        self._items[schedule.id] = schedule

    def upsert(self, schedule: Schedule) -> None:
        """Insert or replace by id."""
        self._items[schedule.id] = schedule

    def delete(self, schedule_id: str) -> bool:
        """Remove the schedule. Returns True if it existed, False if not."""
        return self._items.pop(schedule_id, None) is not None

    def get(self, schedule_id: str) -> Schedule | None:
        return self._items.get(schedule_id)

    def all(self) -> list[Schedule]:
        """All schedules in insertion order."""
        return list(self._items.values())

    def enabled_schedules(self) -> list[Schedule]:
        """Only those with enabled=True, in insertion order."""
        return [s for s in self._items.values() if s.enabled]

    # ── Serialization ───────────────────────────────────────────────
    def to_serializable(self) -> list[dict[str, Any]]:
        """A JSON-safe list of schedule dicts for HA storage."""
        return [s.to_dict() for s in self._items.values()]

    @classmethod
    def from_serializable(cls, data: list[dict[str, Any]]) -> ScheduleStore:
        """Build a fresh store from the serialized form."""
        store = cls()
        for d in data:
            store._items[d["id"]] = Schedule.from_dict(d)
        return store


def is_within_active_window(sched: Schedule, check_date: date) -> bool:
    """Pure-logic check: is `check_date` within `sched`'s active window?

    Used by the run_planner to filter out firings before start_date or
    after end_date, with optional annual-repeat semantics.

    • repeat_annually = False (default): start_date / end_date are
      absolute one-shot bounds. check_date must satisfy
      start_date <= check_date <= end_date (whichever bounds are set).
    • repeat_annually = True: only the (month, day) of start/end are
      compared, year ignored. The window is required to be within a
      single calendar year (enforced at construction).
    """
    if not sched.repeat_annually:
        if sched.start_date is not None and check_date < sched.start_date:
            return False
        return not (sched.end_date is not None and check_date > sched.end_date)
    # Annual repeat — validation guarantees both dates are set + non-wrap.
    cur = (check_date.month, check_date.day)
    start = (sched.start_date.month, sched.start_date.day)
    end = (sched.end_date.month, sched.end_date.day)
    return start <= cur <= end
